# Generated by Django 5.2.6 on 2025-10-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_registration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_tier',
            field=models.CharField(choices=[('basic', 'BASIC - 100 products'), ('premium', 'Premium - 1000 products'), ('enterprise', 'Enterprise - Unlimited products')], default='basic', max_length=50),
        ),
    ]
