# Generated by Django 5.2.6 on 2025-10-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_storesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name_plural': 'Store Settings'},
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='mpesa_business_shortcode',
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='mpesa_passkey',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='notification_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mpesa_account_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mpesa_business_shortcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
