# Generated by Django 5.2.6 on 2025-11-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_storesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='shipping_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
