# Generated by Django 5.2.6 on 2025-09-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionpayment',
            options={'ordering': ['-created_at']},
        ),
    ]
